assets:
  - ip: "172.31.69.28"
    role: "web-application-server"
    services: ["http", "https"]
    criticality: "high"
    rationale: "Presentation sample public web server."
  - ip: "172.31.69.25"
    role: "multi-service-server"
    services: ["ssh", "ftp", "http"]
    criticality: "high"
    rationale: "Presentation sample multi-service server."
trust_zones:
  - cidr: "172.31.0.0/16"
    zone: "internal"
  - cidr: "18.0.0.0/8"
    zone: "external-unknown"
  - cidr: "13.0.0.0/8"
    zone: "external-unknown"
